# Generated by Django 4.0.1 on 2022-02-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
