# Generated by Django 4.0.1 on 2022-02-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_delete_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockDaily',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=40, null=True)),
                ('date', models.DateField()),
                ('open', models.BigIntegerField(blank=True, null=True)),
                ('high', models.BigIntegerField(blank=True, null=True)),
                ('low', models.BigIntegerField(blank=True, null=True)),
                ('close', models.BigIntegerField(blank=True, null=True)),
                ('diff', models.BigIntegerField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stock_daily',
                'managed': False,
            },
        ),
    ]
